### ISSUE TITLE
gsi exceptions are not displayed when running from Emacs

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#405]
This shell command:

`tty; echo TERM=$TERM; echo erroneous >erroneous.scm && gsi erroneous.scm; echo "gsi exit code $?"`

Displays the following (as expected) when run from a normal Unix terminal (TERM=xterm):

```
/dev/ttys000
TERM=xterm-256color
*** ERROR IN "erroneous.scm"@1.1 -- Unbound variable: erroneous
gsi exit code 70
```

Emacs `M-x shell` also works as expected:

```
/dev/ttys004
TERM=dumb
*** ERROR IN "erroneous.scm"@1.1 -- Unbound variable: erroneous
gsi exit code 70
```

But with Emacs `M-x shell-command` the exception is not displayed:

```
not a tty
TERM=dumb
gsi exit code 70
```

Possibly related: #370

**Comment by feeley** [comment]
This is related to the (atypical) way Gambit manages REPL interaction.  By default all REPL interaction, including error messages, is on the controlling terminal (usually /dev/tty).  The controlling terminal is often the same as stdin and stdout, but not always, for example when the input and/or output of the program are redirected.  This allows debugging with the REPL programs that read/write from (possibly redirected) stdin/stdout.  For example:

```
% echo 42 | gsi -:dr -e "(pp (+ (read) n))"
*** ERROR IN (string)@1.15 -- Unbound variable: n
> ,(c 5)   ;; continue as though n had the value 5
47
```

Note that the `-:dr` runtime option is simply to tell the Gambit debugger to start a REPL when an exception is raised rather than exiting.

The problem with M-x shell-command is that gsi is started without a controlling terminal, so  when the error occurs the Gambit debugger tries to open the controlling terminal and fails (because emacs' M-x shell-command didn't start gsi with one).

This issue can be solved using the `-:d-` runtime option that forces the Gambit debugger to use stdin/stdout for the REPL:

M-x shell-command gsi -:d- -e erroneous <ret>

**Comment by lassik** [comment]
OK, that makes sense and I can see that it's useful to interactively debug a program that sits in the middle of a pipeline.

What is gsi's policy with using stderr though? Most programs that can redirect both input and output simply write their errors to stderr (though most of them cannot be debugged interactively). There are many situations where a script is run in a batch job and the user may not even have an interactive shell on the computer where the command is running. In that case it would still be vital to display the exception (usually they are displayed to stderr) even when debugging is not possible.

stderr can be redirected too, but if so, it tends to be deliberately redirected to a log file from which the user (or another program) expects to read any error messages.

On the Mac,  M-x shell-command `gsi -:d- -e erroneous` does not display the exception either for some reason. M-x shell and an ordinary terminal emulator display it as expected.

**Comment by feeley** [comment]
Strange, I'm on a mac and it works for me (make sure gsi is found in your PATH).

For stderr I don't know what the best policy is.  I have to think about this.  Gambit's behaviour certainly is surprising to many users, and that's not a good thing even if the I/O model is more powerful.

**Comment by feeley** [comment]
Perhaps the default should be `-:d-` and a user can always do `-:dc` to run the REPL on the controlling terminal (console).  I could also change the REPL channel so it has 3 ports (in, out, and error) and connect the error port to stderr when using `-:d-` (the default).  With `-:dc` all three ports would be the console.

**Comment by lassik** [comment]
My Emacs does find gsi, and says that it exited with code 70 (EX_SOFTWARE from sysexits.h) so all of that is correct. Just the exception message is lost somehow.

I agree that it's probably surprising. More importantly, in case the command is run as a batch job on a remote system (as is increasingly common nowadays that people rent servers and run CI jobs) the current policy may cause error messages to be lost. It is not always possible to recreate the context in which the error happened in order to study it so the messages are valuable to save.

Would it be blasphemous if REPL debugging is disabled by default when gsi is started for the purpose of  running a script as in `gsi foo.scm`? That would probably match the expectations of most users. It could simply write errors to stderr and not use a terminal for anything.

Programmers could still enable REPL debugging manually with a simple flag, as in `gsi -:dc foo.scm`. And when gsi is run as just `gsi` with no script filename, it would of course do REPL debugging.

**Comment by lassik** [comment]
One of the reasons I would disable REPL debugging by default is that scripts are often written like:

```
#! /usr/bin/env gsi
(display "Hello world")
(newline)
```

which gets executed as `/path/to/gsi script-filename`. Users often run those scripts without knowing or caring which programming language they are written in, so getting into a debugger on error is quite surprising (especially to non-programmers). Getting a stack trace on stderr is also surprising, but it's less perplexing because it's non-interactive so there's little the user can do other than copy/paste it into some web forum to ask for help. A REPL can look intimidating to a non-programmer (or even to a programmer not familiar with Lisp/Scheme) since it has an interactive prompt that expects you to type something. People who are not familiar with the system have no idea what to type and what will happen if they type the wrong thing.

**Comment by lassik** [comment]
These thing were simpler back in they day when every user was a programmer and Lisp was the only language on the machine :)

**Comment by feeley** [comment]
Yes, blasphemous. It is not good to have settings change depending on the usage.  It uses up too many neurons in my brain.  I prefer using stdin/stdout/stderr by default for the REPL and error messages, and only going through the console if asked explicitly with `-:dc`.

**Comment by feeley** [comment]
Note that the REPL will not start if you use a filename on the command line, or a `-e expression`. To get a REPL on error you need `-:dr`.  Of course if you have started gsi with no parameter to use it interactively, then errors drop you into a new REPL level.

**Comment by lassik** [comment]
Wait, I didn't understand the precise meaning of the word "console" in the context of Gambit. The manual uses both of the words "console" and "terminal". Are those synonyms or do they refer to different things?

> Note that the REPL will not start if you use a filename on the command line, or a `-e expression`. To get a REPL on error you need `-:dr`.

Ah, I misunderstood that. Then it's the same behavior that most/all other interpreters do. That's good.

**Comment by feeley** [comment]
In other words, a program's logic should be self contained (including handling exceptions), and you (as a programmer) need to signify to the interpreter that you are available and willing to debug the program.

**Comment by lassik** [comment]
That seems exactly right.

**Comment by feeley** [comment]
Terminal = isatty, and console = /dev/tty = controlling terminal.

**Comment by feeley** [comment]
For example, a serial port is a tty and so is a pty.

**Comment by feeley** [comment]
The manual also uses the term "REPL channel" which is an abstraction connecting to one of:
1) controlling terminal
2) stdin/stdout
3) a telnet connection (try `-:d@` then `telnet localhost 44555`)
4) an ide
5) etc

**Comment by feeley** [comment]
By the way there is also `-:d0` that will suppress error messages and exit quietly with an error status, which is appropriate when you don't want the program to reveal anything about its inner workings.

**Comment by lassik** [comment]
Thanks for explaining it. All of those make sense.

I tried `gsi -e erroneous` on FreeBSD and Linux emacs (both command line versions) and it causes the same problem.

**Comment by feeley** [comment]
Fixed by defd6819cf93f8bfd5b54715f0442834bd80074f

**Comment by lassik** [comment]
Thanks for attending to this.

I still get the Emacs bug even with `gsi -:d-` and `gsi -:dq`. Can you reproduce it? On mac, an easy way is to do `/usr/bin/emacs -q` in a shell and then esc-x `shell-command` `gsi -:dq -e erroneous`.

**Comment by feeley** [comment]
On my end I get in the minibuffer the message `*** ERROR IN (string)@1.1 -- Unbound variable: erroneous`.  Have you `make install`?  Which gsi is being executed? Note that now you don't even need the `-:d-`.

**Comment by lassik** [comment]
Have some pertinent changes been made between the 4.9.3 release and this latest commit to master?

I just built:

`$ gsi/gsi -v
v4.9.3 20180930122740 x86_64-apple-darwin18.7.0 "./configure"`

from the release tarball and it has the same problem in Emacs.

**Comment by feeley** [comment]
You have to build from the github repo HEAD!  The v4.9.3 release was some time ago... lots of goodies since then!

**Comment by lassik** [comment]
OK, I finally managed to build HEAD by first building from `gambit-v4_9_3.tgz`, copying the gsc/gsc and gsi/gsi binaries resulting from that build into the Git clone's tree and then building in the Git clone.

Can confirm that your fix works. Thank you!

**Comment by feeley** [comment]
It needn't be that complex to build HEAD...  Did the following not work?

```
git clone https://github.com/gambit/gambit.git
cd gambit
./configure
make
```

**Comment by lassik** [comment]
Well, I tried it again and it does! Is ./gsc-boot in fact the only binary it uses for the bootstrap, and the gsc/gsc and gsi/gsi I copied had no effect?

I wasn't able to build HEAD before, even with a fresh build of 4.9.3 underneath. It was probably some mistake on my part since the commit log doesn't show any compiler changes in the last week.

BTW I recommend following these de facto standard conventions for Git commit messages: https://chris.beams.io/posts/git-commit/. The gist of it is to write them like emails, with a very brief subject line and any details after a blank line. Makes the commit log easy to browse.

**Comment by feeley** [comment]
The executable gsc-boot is the compiler used for bootstrapping (compiling the .scm files to .c files).  It is a copy of gsc/gsc (for a recent version of Gambit).  Just copying gsc/gsc and gsi/gsi will have no effect on the build process.

The build process is sensitive to the presence of `gsc-boot` and the `boot` subdirectory.  The `boot` subdirectory is where `gsc-boot` is built for a recent version of Gambit (first by building the latest release, and using that to build a working gsc compiler with the latest sources in the gsc subdirectory).  So instead of cloning from the repo you could also:

```
rm -rf boot gsc-boot
./configure
make
```

This is very likely to work and it is my fallback recipe when a simple `make` does not work.  And if that fallback recipe does not work for some reason then I fallback on `git clone ...`.  If that doesn't work, I manually build `gsc-boot` (possibly with some tweaks to the sources to avoid a bootstrapping issue), and then `make bootclean;./configure;make`.

**Comment by lassik** [comment]
Good to know! Once again, thanks for detailed explanation. So the `boot/` directory is a copy of the Gambit source tree at a stable point in time and `gsc-boot` is the binary compiled from that directory?

**Comment by feeley** [comment]
Yes, with the not so small detail that the `boot` subdir starts off as a copy of Gambit at the last release, then boot/gsc/gsc is built, then the source code in the gsc subdirectory of HEAD is put in that boot/gsc, then boot/gsc/gsc is built again using the previously built gsc, and finally that gsc becomes `gsc-boot`.

**Comment by lassik** [comment]
BTW just noticed that `gsc` has the same problem with disappearing error messages in Emacs M-x shell-command (but the messages are displayed just fine in M-x shell). Built from HEAD.
